import { Incident, AnalyticsDataPoint, ResolutionDataPoint, ClosureDataPoint } from './types';

export const SEED_INCIDENTS: Incident[] = [
  {
    id: 'inc-1',
    type: 'Collision',
    cause: 'Driver Error',
    corridor: 'Outer Ring Road (Silk Board)',
    zone: 'Beta Sector',
    vehicleType: 'Multiple',
    time: '14:15',
    address: 'Silk Board Junction, Outer Ring Rd, Bengaluru',
    lat: 12.9174,
    lng: 77.6228,
    burdenScore: 94,
    priority: 'CRITICAL',
    status: 'Active',
    officersRequired: 5,
    targetZones: 'Sector B4',
    barricadingType: 'Hard, Perimeter-style',
    diversionMain: 'HSR Layout Main Rd',
    diversionAlt: 'Madiwala Underpass',
    priorityConfidence: 98,
    closureConfidence: 95,
    durationConfidence: 89,
    roadClosure: true,
    estDurationMin: 90,
    reportedAt: new Date(Date.now() - 3600000)
  },
  {
    id: 'inc-2',
    type: 'Breakdown',
    cause: 'Mechanical',
    corridor: 'Marathahalli Bridge corridor',
    zone: 'Gamma Sector',
    vehicleType: 'Commercial Truck',
    time: '13:45',
    address: 'Marathahalli Bridge, near multiplex, Bengaluru',
    lat: 12.9562,
    lng: 77.7011,
    burdenScore: 78,
    priority: 'HIGH',
    status: 'Active',
    officersRequired: 3,
    targetZones: 'Sector G2',
    barricadingType: 'Soft, Cone-style',
    diversionMain: 'HAL Old Airport Rd',
    diversionAlt: 'Varthur Rd',
    priorityConfidence: 89,
    closureConfidence: 82,
    durationConfidence: 78,
    roadClosure: false,
    estDurationMin: 45,
    reportedAt: new Date(Date.now() - 7200000)
  },
  {
    id: 'inc-3',
    type: 'Infrastructure Failure',
    cause: 'Environmental',
    corridor: 'Koramangala 80ft Rd',
    zone: 'Alpha Sector',
    vehicleType: 'Passenger Car',
    time: '12:30',
    address: 'Koramangala 80ft Rd, near 4th block, Bengaluru',
    lat: 12.9352,
    lng: 77.6244,
    burdenScore: 45,
    priority: 'MODERATE',
    status: 'Active',
    officersRequired: 2,
    targetZones: 'Sector A3',
    barricadingType: 'Barrier Tape',
    diversionMain: 'Wipro Park Rd',
    diversionAlt: '100 Feet Rd',
    priorityConfidence: 75,
    closureConfidence: 68,
    durationConfidence: 82,
    roadClosure: false,
    estDurationMin: 30,
    reportedAt: new Date(Date.now() - 10800000)
  },
  {
    id: 'inc-4',
    type: 'Weather Hazard',
    cause: 'Environmental',
    corridor: 'NICE Ring Road',
    zone: 'Alpha Sector',
    vehicleType: 'Multiple',
    time: '14:30',
    address: 'NICE Road exit, near Bannerghatta intersection, Bengaluru',
    lat: 12.8718,
    lng: 77.4831,
    burdenScore: 78,
    priority: 'HIGH',
    status: 'Active',
    officersRequired: 3,
    targetZones: 'A / B',
    barricadingType: 'Hard, Perimeter-style',
    diversionMain: 'NICE Road exit',
    diversionAlt: 'Bannerghatta Rd',
    priorityConfidence: 94,
    closureConfidence: 88,
    durationConfidence: 72,
    roadClosure: true,
    estDurationMin: 47,
    reportedAt: new Date(Date.now() - 150000)
  }
];

export const VOLUME_DATA: AnalyticsDataPoint[] = [
  { time: '00:00', events: 120, baseline: 90 },
  { time: '04:00', events: 80, baseline: 75 },
  { time: '08:00', events: 450, baseline: 380 },
  { time: '12:00', events: 380, baseline: 350 },
  { time: '16:00', events: 520, baseline: 410 },
  { time: '20:00', events: 210, baseline: 190 },
  { time: '24:00', events: 140, baseline: 110 }
];

export const RESOLUTION_DATA: ResolutionDataPoint[] = [
  { cause: 'Potholes', days: 8.7 },
  { cause: 'Signal Failure', days: 3.2 },
  { cause: 'Debris', days: 1.5 },
  { cause: 'Accident', days: 0.4 },
  { cause: 'Waterlog', days: 2.1 }
];

export const CLOSURE_DATA: ClosureDataPoint[] = [
  { cause: 'Debris', prob: 100 },
  { cause: 'Accident', prob: 85 },
  { cause: 'Waterlog', prob: 60 },
  { cause: 'Signal Failure', prob: 30 },
  { cause: 'Potholes', prob: 5 }
];
